version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  clickhouse-01:
    image: yandex/clickhouse-server
    hostname: clickhouse-01
    container_name: clickhouse-01
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DB=olap_cluster
    ports:
      - "8123:8123"
      - "9109:9009"
      - "9100:9000/tcp"
    volumes:
      - ./clickhouse_conf/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse_conf/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse_conf/macros/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./clickhouse_conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse_data/server-01:/var/lib/clickhouse
    depends_on:
      - zookeeper

  clickhouse-02:
    image: yandex/clickhouse-server
    hostname: clickhouse-02
    container_name: clickhouse-02
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_DB=olap_cluster
    ports:
      - "8223:8123"
      - "9209:9009"
      - "9200:9000/tcp"
    restart: unless-stopped
    volumes:
      - ./clickhouse_conf/clickhouse_config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse_conf/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./clickhouse_conf/macros/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./clickhouse_conf/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse_data/server-02:/var/lib/clickhouse
    depends_on:
      - zookeeper

  trino-master:
    build: ./trino_conf
    ports:
      - "8080:8080"
    volumes:
      - ./trino_data/master:/var/lib/trino/data
      - ./trino_conf/coordinator_config.properties:/opt/trino/etc/config.properties
      - ./trino_conf/etc/catalog:/opt/trino/etc/catalog

  trino-worker:
    build: ./trino_conf
    volumes:
      - ./trino_data/worker:/var/lib/trino/data
      - ./trino_conf/worker_config.properties:/opt/trino/etc/config.properties
      - ./trino_conf/etc/catalog:/opt/trino/etc/catalog

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
